version: "3.8"
services:
  mongo_db:
    container_name: mongo_db_iad
    image: mongo:7
    restart: unless-stopped
    ports:
      - "${MONGO_LOCAL_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
